### ISSUE TITLE
SQLite Syntax error trying to launch AttackSurfaceAnalyzer-GUI on Fedora 30

### ISSUE THREAD

**Issue by petemcdonnell** [microsoft/AttackSurfaceAnalyzer#214] opened 2019-05-23 13:05 UTC
**Describe the bug**
After downloading and extracting the AsaGui-slim-linux-2.1.19.tar.gz package, I attempted to run the application, but if failed to launch and displayed an error.

**To Reproduce**
1. Download and extract AsaGui-slim-linux-2.1.19.tar.gz
2. attempt to run the application as shown in the output below
3. See error:

```

user@host AsaGui-slim-linux-2.1.19]$ sudo ./AttackSurfaceAnalyzer-GUI 
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {472519ac-a516-45b8-8c28-83aa2d093dcd} may be persisted to storage in unencrypted form.
Application startup exception: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'near "-": syntax error'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at AttackSurfaceAnalyzer.Utils.DatabaseManager.Setup() in /home/vsts/work/1/s/Lib/Utils/DatabaseManager.cs:line 98
   at AttackSurfaceAnalyzer.Gui.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /home/vsts/work/1/s/Gui/Startup.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'near "-": syntax error'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at AttackSurfaceAnalyzer.Utils.DatabaseManager.Setup() in /home/vsts/work/1/s/Lib/Utils/DatabaseManager.cs:line 98
   at AttackSurfaceAnalyzer.Gui.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /home/vsts/work/1/s/Gui/Startup.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'near "-": syntax error'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at AttackSurfaceAnalyzer.Utils.DatabaseManager.Setup() in /home/vsts/work/1/s/Lib/Utils/DatabaseManager.cs:line 98
   at AttackSurfaceAnalyzer.Gui.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /home/vsts/work/1/s/Gui/Startup.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at AttackSurfaceAnalyzer.Gui.Program.Main(String[] args) in /home/vsts/work/1/s/Gui/Program.cs:line 14
Aborted

```

**Expected behavior**
The application launches

**System Configuration (please complete the following information):**
 - OS: Fedora 30 x86_64
 - OS Version: Fedora 30 x86_64
 - Application Version: 2.1.19
 - CLI or GUI: Slim GUI

**Comment by sweeper85** [comment] 2019-05-23 16:01
Getting same error with version 2.1.19 on Ubuntu 18.04.2 LTS.

**Comment by gfs** [comment] 2019-05-23 16:57
Please use the 2.0 release. 2.1 is the development branch and shouldn't be relied on for production use. I have a fix for this pending, however.

**Comment by gfs** [comment] 2019-05-23 16:58
Duplicate of #212.

**Closed by gfs** 2019-05-23 16:58 UTC
Labels: bug
