### ISSUE TITLE
Restrict length of runid names

### ISSUE THREAD

**Issue by Guydalf** [microsoft/AttackSurfaceAnalyzer#173] opened 2019-05-01 00:49 UTC
**Describe the bug**
After creating several scans, subsequent scans do not appear in the UI list for Results to choose from though they do exists in the DB and Scan UI prevents from reusing the same id.  This is a blocking issue.

**To Reproduce**
1. Create 19+ scans and note that subsequent ones are not shown in the results selection lists

**Expected behavior**
The results selection drop downs should not be limited.  Should be able to see all scans created to select.

**Screenshots**
![createscannotshowninresults](https://user-images.githubusercontent.com/47648296/57001869-fe176a00-6b6f-11e9-9027-e765a378343b.png)
![limitedresultslist](https://user-images.githubusercontent.com/47648296/57001879-08d1ff00-6b70-11e9-96e6-fe870d1898a1.png)

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - Application Version: 2.1...see image
 - CLI or GUI: GUI

**Additional Context**

**Comment by gfs** [comment] 2019-05-02 04:18
I can't reproduce this. I get a scroll bar both in an external browser with the slim gui and in the electron interface. @Guydalf can you try again without the super long run names? The scroll bar might be there but just off the edge of the screen.

![image](https://user-images.githubusercontent.com/98900/57056301-69d40280-6c56-11e9-8aac-672023788522.png)

**Comment by Guydalf** [comment] 2019-05-02 22:03
![withlongrunid](https://user-images.githubusercontent.com/47648296/57109839-6474c780-6ceb-11e9-9cad-a879aefc10a4.png)
It was related to UI testing with very large runId values.  What happens is it makes the vertical scrollbar disappear so you can't see the new item which depending on selling may appear offscreen unless you use the mouse arrow up/down keys.  So, I'll rename this to just indicate the UI issue instead but not a high priority issue to fix.  It wouldn't be hard to limit the input max size either so your call.

**Comment by gfs** [comment] 2019-05-03 19:05
It is impossible to 'fix' the way that electron is handling large run ids. I think the only possible way to catch this edge case is to limit run id names. I consider this very low priority. It sounds like the scrolling still works.

**Comment by gfs** [comment] 2019-12-28 03:31
Closing as Won't Fix. I'd rather have predictable behavior (accept any valid name) than have to add extra feedback for a length restriction, particularly thinking about scripted runs which may have dynamic run names based on where the script is executing etc.

**Closed by gfs** 2019-12-28 03:31 UTC
Labels: enhancement
