### ISSUE TITLE
DEP and ASLR Flags reported as false positive

### ISSUE THREAD

**Issue by Kurosaki22** [microsoft/AttackSurfaceAnalyzer#655] opened 2022-06-22 10:46 UTC
**Describe the bug**
Files with active DEP and ASLR flags are reported as false positive.
We are facing the issue that files which are verified to have DEP and ASLR activated reported that theses flags are missing.

**To Reproduce**
Run ASA GUI as Admin
Use Guided Mode
Select "Enable FileSystem Collector"
Let ASA analyze the system and wait until is in monitoring mode and you can perform changes
Install any software and launch it.
Close the software and stop the monitoring of ASA

**Expected behavior**
Files with DEP and ASLR are not reported as false positive

**Screenshots**
![image](https://user-images.githubusercontent.com/69061840/175010842-42eafb41-c6f2-4d6a-a011-f366586b6634.png)

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 11 21H2 (OS Build 22000.258)
 - Application Version: 2.3.282
 - CLI or GUI: GUI (as Administrator)

**Additional Context**
JSON export of an Microsoft binary as example
[JSON report example.txt](https://github.com/microsoft/AttackSurfaceAnalyzer/files/8956850/JSON.report.example.txt)

**Comment by gfs** [comment] 2022-06-22 20:23
I can reproduce this with a netstandard.dll I have locally.

**Comment by gfs** [comment] 2022-06-22 22:10
The root cause was an oversight in the default OAT Contains and Contains Any operations. Fix is here: https://github.com/microsoft/OAT/pull/147 after merged I'll update ASA's dependencies and confirm it fixes the issue and push a new version with the updated lib.

**Comment by Kurosaki22** [comment] 2022-06-22 22:17
Sounds good. Thanks for your effort :)

**Comment by gfs** [comment] 2022-06-22 23:21
I just merged a commit that seems to fix this in my testing. 

Thanks for your report, and don't hesitate to reach out if you have additional issues.

**Closed by gfs** 2022-06-22 23:21 UTC
Labels: bug
