### ISSUE TITLE
Fails to detect Firewall policy change 

### ISSUE THREAD

**Issue by Guydalf** [microsoft/AttackSurfaceAnalyzer#306] opened 2019-10-23 22:39 UTC
**Describe the bug**
Select a firewall policy like outgoing network communications for Candy Crush.  Run ASA.  Change the policy e.g. from Allow or enable to disabled.  Run ASA.  Note the change is not detected.  I have seen it work but not consistently...Spotify for instance but not CC.  Also for Spotify it reports a page worth of policy changes...might be same change I will check and update in comments.

**Expected behavior**
Report the change in policy

**Screenshots**
See screenshot

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: [e.g. Windows 10 1803]
 - Application Version: [e.g. 2.1.30-beta
 - CLI or GUI: GUI
![asabug3](https://user-images.githubusercontent.com/47648296/67439514-49ed1e00-f5ab-11e9-930f-eb39ba18d6d1.png)

**Additional Context**

**Comment by gfs** [comment] 2019-10-23 23:52
If the data isn't surfaced out of the API I call I cannot do anything about it.  However, I also cannot reproduce this.

**Comment by Guydalf** [comment] 2019-10-24 17:46
I can consistently but I'll send you a video.

**Comment by gfs** [comment] 2019-11-14 06:17
Try again with the latest.  Here's what I did that does work:

Open Control Panel
Navigate to "Windows Defender Firewall"
Navigate to "Advanced Settings"
Select "Inbound Rules"
Open an Administrator terminal window
Run `asa.exe collect -F`
Right Click a Rule and Delete it
Right Click another Rule and Disable it
Run `asa.exe collect -F`
Run `asa.exe export-collect`

**Comment by gfs** [comment] 2019-11-14 21:25
I've also repro'd the correct behavior in the GUI.  I suspect this may have been caused by a known issue which is now fixed.

**Closed by gfs** 2019-11-14 21:25 UTC
Labels: bug
