### ISSUE TITLE
Generate Analysis Results in HTML

### ISSUE THREAD

**Issue by hardikamin** [microsoft/AttackSurfaceAnalyzer#539] opened 2020-09-03 02:48 UTC
**Is your feature request related to a problem? Please describe.**
asa.sqlite is not usable easily. For every command run, it does not show where(and which) the files are generated and saved.
Export to json is not working as expected. It does not work from GUI; or it does not show if it's completed and where file is stored.
Results are not easily readable.

**Describe the solution you'd like**
HTML reports as it used to generate in ASA 1.0/older will be great. Or is there already a way to do so; how?

**Describe alternatives you've considered**
A proper json/txt/csv file would help as an alternative

**System Configuration (please complete the following information):**
* OS: Windows
* Application Version: v.2.2.57+7af37f8172
* CLI or GUI: Both

**Additional context**
Is there a detailed document on using CLI mode. Current wiki does not have much info except to follow 'asa.exe help'

**Comment by gfs** [comment] 2020-09-03 15:17
Thanks for your report and sorry you're having issues with the GUI.

We are doing a full rewrite of the GUI and are planning to launch a beta in the next week or two.  At that point we'd love to  get more feedback on the new interface.  It does look like downloading the json results isn't working from the current GUI.  That will be fixed in the new GUI.

We don't have detailed documentation for using the Cli.  I opened a new issue to track that for 2.3 #540.  Is there any particular place you're stuck using the help options?

For now, you're probably interested in the `collect` and `export-collect` commands.

Run `asa collect --help` to see the options available for collecting.

For example: `asa collect -f --directories C:\` to scan the C drive for files.

Run `asa export-collect --help` to see the options available for analyzing and exporting results to json.

If you just want to compare the last two runs you made just run `asa export-collect` and it will automatically use the last two runs.

**Comment by hardikamin** [comment] 2020-09-03 18:30
@gfs , thank you for considering this request. We'll surely work on new revision as soon as it's out and provide feedback.
As of now our main concern is to get Analysis Results in HTML/JSON format. We're using ASA 1.0 for long time and looking for similar options for results.

Yes, we'll be mostly using CLI in our automation testing; so please share as much details possible. We already have test framework with ASA 1.0 so mostly we'd clone that with latest ASA version.

In particular, we're looking for steps for CLI mode similar to what's explained in wiki for GUI mode; specially generating analysis reports in human readable format. 'asa.sqlite' does not seem so convenient as compared to HML/JSON options.
I could not find where does it store the collections and output results.

Thanks again.

**Comment by hardikamin** [comment] 2020-09-03 19:07
Thanks for confirming. So in order to use new version now we must rely on json results only. In that case, it would help more if you can **please also add a wiki explaining results in json files**. i.e. how do we parse them to find the possible issues raised by ASA/collectors comparison. In GUI/HTML it's still good to understand the output, but in json it seems difficult.

Also, after a few trials in GUI we found that,
1.No Option to Export Results into JSON File though its mentioned on UI.
2.No Option to Navigate to Results

**Comment by gfs** [comment] 2020-09-03 19:32
>  1.No Option to Export Results into JSON File though its mentioned on UI.

As mentioned previously in this thread, that appears to be a bug.

>  2.No Option to Navigate to Results

I can't reproduce this.  Viewing results in the GUI is working as expected.

![image](https://user-images.githubusercontent.com/98900/92158905-6c61e180-ede1-11ea-867d-c439e2d17e11.png)

**Comment by gfs** [comment] 2020-09-04 00:35
I created an issue to track documenting the json schema. #541 

I'll try to address the documentation issues next week once we have the 2.3 beta available.

**Comment by gfs** [comment] 2020-09-04 00:37
Closing this issue as won't fix for generating standalone HTML reports.

Will address the documentation issues raised tracking in the linked issues.

**Closed by gfs** 2020-09-04 00:37 UTC
Labels: enhancement
