### ISSUE TITLE
Multiple "Help" forms

### ISSUE THREAD

**Issue by Oleg26Dev** [microsoft/AttackSurfaceAnalyzer#223] opened 2019-06-02 07:41 UTC
Every my click menu "Help" creates separate window. If I click "Scan" or "Results" the "Help" windows disappear

**Comment by gfs** [comment] 2019-06-02 22:56
Hey Oleg,

Can you provide more detail on the OS and ASA version you're using?

**Comment by Oleg26Dev** [comment] 2019-06-03 04:31
I use the latest ASA version: downloaded it from the git 2 days ago, built it for Windows and run in Windows 7.

**Comment by gfs** [comment] 2019-06-03 18:28
I can't reproduce this on any supported platform, either in the Electron or slim GUIs.  There's no mechanism implemented which would close the help menus.

Clicking Help will open a new window each time, that is expected behavior.

When you navigate to scan or results the help windows are not closed. This is expected behavior.

Finally, if you are attempting to build the Electron GUI on Windows 7, that is not currently a platform we support.

**Comment by gfs** [comment] 2019-06-12 18:27
@Oleg26Dev without more info I'll need to close this issue. Let me know if you're still having trouble.

**Closed** 2019-06-17 18:59 UTC
Labels: bug, needs more information
