### ISSUE TITLE
Service Status in Results Summary Is Incorrect 

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#181] opened 2019-05-01 01:51 UTC
**Describe the bug**
I located a service that was normally stopped and usually started manually and started it after taking a baseline scan.  The results shown are unexpected in that the summary status is shown as "Stopped" when in fact the new state is running and therefore a bit misleading as shown in the attached image.  Note the detailed view correctly shows the change from stopped to running.  As a user I am most interested in the resulting change i.e. that it is now running which will prompt me to investigate further.

The reverse is true is I then stop the service, take another snapshot and run the analysis.  The summary state now shows "Running" when in fact it is stopped.

**To Reproduce**
1. Go to local system services in Windows 
2. Find a stopped service and start it e.g. ActiveXInstaller (AxInstSV).  Take an ASA snapshot and compare to baseline
3. See error

**Expected behavior**
Show the new state on the summary i.e. Running or Stopped as the case may actually be at present.

**Screenshots**
![StoppedNowRunningSrv](https://user-images.githubusercontent.com/47648296/57002908-a977ed00-6b77-11e9-9db1-1ca8129ae60f.png)
![RunningNowStopped](https://user-images.githubusercontent.com/47648296/57002951-f1970f80-6b77-11e9-8c69-03d7a34eda69.png)
![cmdservices](https://user-images.githubusercontent.com/47648296/57003047-aa5d4e80-6b78-11e9-990c-c2c289b4d323.png)

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: [e.g. Windows 10 1803]
 - Application Version: [e.g. 2.0.1-beta+50af283871]
 - CLI or GUI: GUI only.  CLI is actually very clear.  See attached.

**Additional Context**

**Comment by gfs** [comment] 2019-05-01 15:17
This is a dupe of #182. The correct current state is there in the third column. The field name "currentstate" means "state at time of collection" not "state at time of displaying results"

**Closed** 2019-05-01 15:17 UTC
Labels: bug
