### ISSUE TITLE
Crash when doing analysis

### ISSUE THREAD

**Issue by lkarlslund** [microsoft/AttackSurfaceAnalyzer#638] opened 2022-03-07 11:39 UTC
Using latest release I did a Windows collection using "Guided Mode", let it collect info, then did the installation and the let it do post install collection. Then the analysis crashed.

Redoing analysis with same capture crashes again. Not sure if this is helpful enough, but here's the crash dump:

```
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Tools\ASA_win_2.3.274
[12:33:03 INF] Completed Comparing in 00h:00m:03s:083ms.
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'xbUAKet0Brd2KYP2ZlabD6QaapHrbMCrtP26Bi6dZ0g'.
      System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
       ---> System.NullReferenceException: Object reference not set to an instance of an object.
         at Microsoft.CST.AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerClient.<>c__DisplayClass37_0.<CompareRuns>b__0(CompareResult res) in D:\a\1\s\Cli\AttackSurfaceAnalyzerClient.cs:line 1186
         at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
         at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
         at System.Linq.Parallel.SpoolingTaskBase.Work()
         at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
         --- End of inner exception stack trace ---
         at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
         at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
         at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
```

**Comment by lkarlslund** [comment] 2022-03-07 15:43
FYI: I tried with a new capture, and got exact same crash.

**Comment by gfs** [comment] 2022-03-07 16:19
Thanks for your report. Sorry you're having issues. I'll take a look today. 

What command line options did you use?

**Comment by gfs** [comment] 2022-03-07 18:06
I am unable to reproduce this running via Visual Studio or via the package in the releases when using the file System collector and monitoring - based on where the crash it seems to be related to what is being output by one of the collectors.  Based on visual studio's null tracing none of the objects on the referenced line should be able to be null however.

I understand you may not be able to but if you are able to share the database files that are generated when you encounter this error that would be helpful.

**Comment by lkarlslund** [comment] 2022-03-08 08:28
Thank you for the followup. I ran "asa gui" and used these settings for collection:

![image](https://user-images.githubusercontent.com/8929787/157196131-3c820212-4bd8-4bc5-948f-d883ad9ce595.png)

The machine is a fairly fresh install of Windows 11, but maybe ASA hits a folder/file or something with a name or otherwise it doesn't like? (Guessing)

**Comment by gfs** [comment] 2022-03-08 18:25
Thanks for the extra info. 

I'll try a run with these selections.

**Comment by gfs** [comment] 2022-03-09 03:33
I have not been able to replicate this.  I am running 2.3.275 as downloaded from the GitHub Releases page on Windows 11 and successfully ran a guided session with these settings.

Here are some further debugging steps you might be able to try:

# Enable more logging on the console
`asa <command> --debug`
`asa <command> --verbose`

# Rerun analysis for the last two Collect runs.
Guided mode runs two Collect runs and a monitor run. This should rerun the analysis just for the collect runs.
`asa export-collect`

# Rerun analysis for the last monitor run.
This should rerun the analysis just for the monitoring run.
`asa export-monitor`

With the above you can at least identify if the analysis is failing on the Monitor runs on the Collect runs (I cannot tell for sure from the content you posted).

In addition, if you can provide the databases which replicate this error, I would be able to more easily identify what is happening.  The asa database is by default split into multiple sqlite shards named `asa.sqlite` and `asa.sqlite_1` through 6.  You will need to include all 'asa.sqlite*' files.

**Comment by Daywalker46410** [comment] 2022-03-09 18:23
I am running into the same issue.  Unfortunately, I cannot provide screenshots or exports of the system experiencing the issue due to site policies, but I can provide some context.

ASA Version 2.3.274+a57c05889c.

Collection (asa.exe collect -a) works fine.

Comparison (asa.exe export-collect --disableanalysis) works fine.

SIngle-run analysis (asa.exe --exportsinglerun --secondrunid) works fine, irrespective of which runid I use.

Analysis between two runs, either by specifying the runids or letting the tool use the last two runs fails on an "Object reference not set to an instance of an object" error.

**Comment by gfs** [comment] 2022-03-09 18:29
Thanks @Daywalker46410 for that additional info. This helps narrow it down. 

If the log is small enough to skim, if you examine the results you get from export --disableanalysis are there any obvious aberrations/nulls and if so can you tell what collector they came from?

**Comment by gfs** [comment] 2022-03-09 19:13
I have a PR #641 for a version that will add additional logging around this issue. Once it is released, use your existing database that causes the crash and try either `asa export-collect --debug --SingleThreadAnalysis` or `asa export-collect --verbose --SingleThreadAnalysis`.  Check the console output for the stack trace and information about the object that caused the crash.  Single the exception should be caught it may have multiple outputs.

This change should prevent the crash but does not address the root issue that there is not supposed to be a null at this point.

**Comment by gfs** [comment] 2022-03-09 20:43
https://github.com/microsoft/AttackSurfaceAnalyzer/releases/tag/v2.3.276 is now available with additional logging for this issue.

**Comment by gfs** [comment] 2022-03-10 23:41
Should be fixed in the latest.

**Closed by gfs** 2022-03-10 23:41 UTC
Labels: bug
