### ISSUE TITLE
ASA GUI does not launch v2.1 

### ISSUE THREAD

**Issue by no-good-usernames-left** [microsoft/AttackSurfaceAnalyzer#213] opened 2019-05-23 11:57 UTC
**Describe the bug**
GUI does not open in the v2.1 release on Windows 10 or Server2012

**To Reproduce**
1. Download 2.1 for Windows 10 or WinSlim
2. Attempt to execute it or launch the program
3. Nothing  happens but the app is running in the background
4. WinSlim just slings a bunch of code on the screen and then crashes

**Expected behavior**
A GUI to launch fairly quickly

**Comment by gfs** [comment] 2019-05-23 16:58
Thanks for the feedback.  Please use the 2.0 release. 2.1 is an alpha version and should not be used for production use. Duplicate of #212.

**Closed by gfs** 2019-05-23 16:58 UTC
Labels: bug
